# Generated by Django 5.0.7 on 2024-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isReporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
